# fly.toml app configuration file generated for job-board-7ll5iq on 2024-12-22T02:25:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'job-board-7ll5iq'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
